### ISSUE TITLE
Take into account WhiteSpaceCharacters attribute 

### ISSUE THREAD

**Issue by istanishev** [Cimpress-MCP/PostalCodes.Net#22]
Currently, the WhiteSpaceCharacters attribute inside the json description for each postal code is not used correctly. It should be passed to the base class to be able to handle white spaces correctly.

**Comment by rnowosielski** [comment]
```WhiteSpaceCharacters``` could possibly be renamed to something like ```RedundantCharacters``` or something that better exposes the meaning of this configuration. 

These are actually the characters that could be safely stripped off from the postal code without altering its meaning.

**Comment by istanishev** [comment]
Nice :)
