### ISSUE TITLE
Add support for all the countries using numeric postal codes

### ISSUE THREAD

**Issue by rnowosielski** [Cimpress-MCP/PostalCodes.Net#28]
For the NextBigThing we should probably support all the postal code formats mentioned on the [wikipedia page](http://en.wikipedia.org/wiki/List_of_postal_codes). That would probably be a sufficient start.

**Comment by rnowosielski** [comment]
Let's start with numeric codes because they are much easier to add. With the more complicated cases let's do a pull model approach - whoever needs support for a particular "exotic" zip code, should file a ticket and we can address that as we go.

**Comment by istanishev** [comment]
Agree ;)

**Comment by rnowosielski** [comment]
This has already been done, so I am closing this ticket. For all *exotic* postal codes please file separate tickets to address missing or misconfigured countries.
