### ISSUE TITLE
CreateCountry should throw ArgumentExceptions instead of InvalidOperationExceptions?

### ISSUE THREAD

**Issue by wenceslauslee** [Cimpress-MCP/PostalCodes.Net#52]
When we call CountryFactory.CreateCountry("HECK"), we get an InvalidOperationException with error message "The specified country code is not valid: HECK". This makes me think that it should be throwing an ArgumentException instead of an InvalidOperationException?

**Comment by istanishev** [comment]
Fixed in 2.0.2.163
