### ISSUE TITLE
NL Postal codes should not allow left padding, and can not start with a `0`

### ISSUE THREAD

**Issue by Cerbrus** [Cimpress-MCP/PostalCodes.Net#73]
Currently, these postal codes pass validation:

`0011aa`
`11` (This gets left-padded to `0011`)

The numeric part of Dutch postal codes should follow the format `[1-9][0-9]{3}`, so at very least, the left-padding should be disabled.

The regex is implemented correctly in `postal-codes-js`:

https://github.com/Cimpress-MCP/postal-codes-js/blob/master/formats/NL.json

**Comment by Cerbrus** [comment]
@istanishev would it be possible to get a response on this issue and the related pull request?

If this can't be implemented, that's okay, but then I'll have to handle those cases separately.

Thanks for your time and this very useful library 🥇

**Comment by Cerbrus** [comment]
@mmaruniak I did, and I mentioned that on the pull request:

> Apparently there are some unit tests in place that consider postal codes starting with a `0` to be valid. I'm not too sure how to update those tests without breaking other cases, since I can't get the project to run locally (_"NuGet exited with code 3"_)

**Comment by mmaruniak** [comment]
Resolved by #74
